### ISSUE TITLE
Internal Server Error (HTTP 500)

### ISSUE THREAD

**Issue by supritsh** [openaps/openaps#119]
Please help,  I'm very new to openstack , I have installed openstack kilo setup. I tried to install openstackclient using pip and did some other stuffs and later I ended up with series of  issues, I managed with the earlier issues but I'm trying to figure out this issue

# openstack token issue
Ignoring domain related config project_domain_id because identity API version is 2.0
Ignoring domain related config user_domain_id because identity API version is 2.0
Ignoring domain related config project_domain_id because identity API version is 2.0
Ignoring domain related config user_domain_id because identity API version is 2.0
Ignoring domain related config project_domain_id because identity API version is 2.0
Ignoring domain related config user_domain_id because identity API version is 2.0
Ignoring domain related config project_domain_id because identity API version is 2.0
Ignoring domain related config user_domain_id because identity API version is 2.0
Failed to discover available identity versions when contacting http://controller:35357/v3. Attempting to parse version from URL.
Internal Server Error (HTTP 500)

**Comment by scottleibrand** [comment]
This seems to be an openstack issue, which is completely unrelated to OpenAPS.
