### ISSUE TITLE
Page Not Found Error

### ISSUE THREAD

**Issue by jdaccarett** [openaps/openaps#123]
In the CONTRIBUTING.md the following link is showing a "Page Not Found Error".

https://openaps.gitbooks.io/building-an-open-artificial-pancreas-system/content/docs/Overview/contribute.html

Screenshot of broken link location in CONTRIBUTING.md
<img width="446" alt="screen shot 2017-05-22 at 9 28 14 am" src="https://cloud.githubusercontent.com/assets/18392071/26318951/e0dc79ac-3ed1-11e7-8fab-6264838f9851.png">

**Comment by danamlewis** [comment]
Thanks! Broken link fixed. https://github.com/openaps/openaps/commit/282ebd72aad65638c853f95ba202fa4bba0ad67c
