### ISSUE TITLE
openaps use pump read_carb_ratios output some hex (expected?)

### ISSUE THREAD

**Issue by amazaheri** [openaps/openaps#13]
ubuntu@ubuntu:~/openaps.alimaz$ openaps use pump read_carb_ratios
0000   0x00 0x14 0x00 0x00 0x00 0x00 0x00 0x00    ........
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0000   0x00 0x14 0x00 0x00 0x00 0x00 0x00 0x00    ........
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0000   0x00 0x14 0x00 0x00 0x00 0x00 0x00 0x00    ........
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0000   0x00 0x14 0x00 0x00 0x00 0x00 0x00 0x00    ........
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
{
  "units": "grams",
  "first": 1,
  "schedule": [
    {
      "i": 20,
      "x": 0,
      "r": 0,
      "ratio": 0,
      "offset": 600
    },
    {
      "i": 0,
      "x": 1,
      "r": 0,
      "ratio": 0,
      "offset": 0
    },
    {
      "i": 0,
      "x": 2,
      "r": 0,
      "ratio": 0,
      "offset": 0
    },
    {
      "i": 0,
      "x": 3,
      "r": 0,
      "ratio": 0,
      "offset": 0
    },
    {
      "i": 0,
      "x": 4,
      "r": 0,
      "ratio": 0,
      "offset": 0
    },
    {
      "i": 0,
      "x": 5,
      "r": 0,
      "ratio": 0,
      "offset": 0
    },
    {
      "i": 0,
      "x": 6,
      "r": 0,
      "ratio": 0,
      "offset": 0
    }
  ]

**Comment by bewest** [comment]
Next version of decocare will fix this, there's a PR from @loudnate to fix. :-)

**Comment by amazaheri** [comment]
BIG LIKE!

**Comment by bewest** [comment]
The latest version has shipped, `sudo easy_install -Z openaps` should bring everything up to date.

**Comment by bewest** [comment]
Thanks for catching this and other issues!

**Comment by amazaheri** [comment]
Thank you guys for fixing stuff :+1:
