### ISSUE TITLE
Glimp 4.15.57 support

### ISSUE THREAD

**Issue by mpessnegger** [openaps/openaps#145]
where to find/download Glimp version 4.15.57? in google store the version listed is 4.14.28 which is not able to send BG data to the AAPS. datatranfer only works via nightscout, which is fine, but unusable in flightmode.

any hint where to download that glimp version highly appreciated
max

**Comment by scottleibrand** [comment]
This repo is for openaps, not AndroidAPS. I don't know the answer off-hand, but the AndroidAPS docs have some pointers on where to go for help: https://androidaps.readthedocs.io/en/latest/EN/Where-To-Go-For-Help/Connect-with-other-users.html
