### ISSUE TITLE
Exit status code with report

### ISSUE THREAD

**Issue by infoneo** [openaps/openaps#34]
Connection with my pump gives an error, but it is not issue right now. 
The problem is, that the report doesn't give correct exit code.

root@rasp:~/a/my1# openaps report show
pump://JSON/read_status/status.json.new
status.json.new  raised  ACK is 0 bytes:

root@rasp:~/a/my1# echo $?
0

But direct command returns correct exit code:

root@rasp:~/a/my1# openaps use pump status
[lots of output]
decocare.errors.AckError: ACK is 0 bytes:

root@rasp:~/a/my1# echo $?
1

**Comment by loudnate** [comment]
This was fixed in ffbbb73a4018fecb8f05281b8128277f7eef7f6b.

**Comment by infoneo** [comment]
Thanks :)
