### ISSUE TITLE
Reduce level of log verbosity

### ISSUE THREAD

**Issue by scottleibrand** [openaps/openaps#38]
Is there a way to reduce the level of log verbosity openaps / decocare create in /var/log/messages and user.log? Even with daily logrotate, I'm filling up my disk with >2GB of logs.

**Comment by bewest** [comment]
Yes, in the `pump.ini`, set `logAddress = /dev/null` or similarly `logLevel = FATAL`, defaults are `/dev/log` and `WARN` respectively.  For mmeowlink, same values, with the extra one: `DECOCARE_LOG_LEVEL = WARN` is default.  `logAddress` must be a syslog handler (you can send it to papertrail directly if you like).

For `openxshareble`, same rules: `logAddress`, and `logLevel` in your `cgm.ini` defaults are `/dev/log`, and `INFO` respectively.

Closing for now, maybe re-open in docs?
