### ISSUE TITLE
Dexcom `iter_glucose` by hours instead of records

### ISSUE THREAD

**Issue by channemann** [openaps/openaps#39]
Same as https://github.com/openaps/openaps/issues/24 but for Dexcom records. Doesn't require any change to decoding-carelink (obviously), so should simply be a port of `iter_glucose_hours` from the Medtronic device code to the Dexcom device code. I'll give it a go.

**Comment by scottleibrand** [comment]
Is there an equivalent iter_pump_hours command now? If not, that would be even more useful IMO, as the number of pump records per hour is highly variable. 

-Scott




On Thu, Aug 6, 2015 at 4:24 PM -0700, "Chris Hannemann" <notifications@github.com> wrote:












Same as #24 but for Dexcom records. Doesn't require any change to decoding-carelink (obviously), so should simply be a port of iter_glucose_hours from the Medtronic device code to the Dexcom device code. I'll give it a go.

**Comment by loudnate** [comment]
Yep, landed in #25.

**Comment by channemann** [comment]
Submitted PR https://github.com/openaps/openaps/pull/40
