### ISSUE TITLE
Commit message for 'openaps device add <> medtronic <serialNumber>' should obfuscate data

### ISSUE THREAD

**Issue by lukasz-kaniowski** [openaps/openaps#82]
After executing ```openaps-device add <name> medtronic <serial number>``` commit message should not contain serial number.

**Comment by bewest** [comment]
In general it logs the command that was run.  However, there's a way to do this using `openaps import` now that will not log the serial in the commit.

**Comment by bewest** [comment]
Actually, `medtronic` vendor was just modified: now, you can leave out the serial number when creating/adding the device, then use `openaps use pump config --serial 123456` to reconfigure it later without leaving a public trace. :-D  Believe this is in latest release, closing for now.
