### ISSUE TITLE
Don't hard-code timezone

### ISSUE THREAD

**Issue by scottleibrand** [openaps/openaps#93]
Running `openaps report add monitor/pumphistory-zoned.json JSON tz rezone monitor/pumphistory.json` hard-codes the current timezone into openaps.ini, such that zoning doesn't work properly when traveling, or presumably when timezone adjusts for DST.  Removing the timezone line from openaps.ini makes it simply use the rig's local timezone at runtime.  That should be the default behavior.

**Comment by bewest** [comment]
FWIW, this was fixed in last release.  Also that's what happens when you use `oref0 template` :-). 
```
$ openaps report add foo JSON tz rezone  foobar.json
added tz://JSON/rezone/foo

$ openaps report show foo --cli
openaps use tz rezone --adjust "missing" --date "timestamp dateString start_at end_at created_at" --astimezone foobar.json

```
